# Generated by Django 5.1.7 on 2025-04-01 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('agree', 'Stimme zu'), ('neutral', 'Neutral'), ('disagree', 'Stimme nicht zu')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_uuid', models.CharField(max_length=255, unique=True)),
                ('economic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison.economic')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
