# Generated by Django 5.1.7 on 2025-04-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0002_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='economic',
        ),
    ]
