# Generated by Django 5.1.7 on 2025-04-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0003_remove_useranswer_economic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='session_uuid',
            field=models.CharField(max_length=255),
        ),
    ]
