# Generated by Django 5.1.7 on 2025-04-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0004_alter_useranswer_session_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='describtion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='describtion',
            field=models.TextField(blank=True),
        ),
    ]
