# Generated by Django 5.1.7 on 2025-04-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0005_answer_describtion_question_describtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='describtion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='describtion',
            new_name='description',
        ),
    ]
